# Generated by Django 5.2.7 on 2025-10-03 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conatct', '0002_contact_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='created_at',
        ),
    ]
